version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    image: smikulenko/foodgram_beckend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/  
    depends_on:
      - db
    env_file:
      - ./.env   

  frontend:
    image: smikulenko/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  
volumes:
  db_value:
  static_value:
  media_value:
